### ISSUE TITLE
Please comment on buildem_cmake_recipe.cmake#L36

### ISSUE THREAD

**Issue by davidshen84** [willyd/caffe-builder#22]
I found this line https://github.com/willyd/caffe-builder/blob/master/cmake/buildem_cmake_recipe.cmake#L36, is difficult to understand.

Would you please help me understand why we want to build Debug when I specify Release?

**Comment by willyd** [comment]
@davidshen84 I wanted to build Release and Debug in a single click. Also, because of the way CMake works I thought that if a library that depends on another is configured to build only one configuration it may fail to find the other one via `find_package` but this is not based on any hard evidence. It may just work as expected.
