### ISSUE TITLE
Support for dll

### ISSUE THREAD

**Issue by Geekrick88** [willyd/caffe-builder#3]
Thank you for the great effort. Everything builds like a charm. I was wondering about what additional effort is required to make shared libraries possible. I have to integrate Caffe with a huge .net project. The only way I can properly interop is by building a managed dll wrapper around it. I tried the following 
1. defined the usual __declspec(dllexport)/import based on CMAKE header CAFFE_EXPORTS.
2. Added this definition to every Register Class and Instantiate class. This works without GPU. If GPU support is added the forward and backward GPU functions throw weird error saying dllimport is not allowed in definition, even though the macro is defined as dllexport in all those files. 
I was wondering if you have a working solution.
Kind Regards,
Rick

**Comment by willyd** [comment]
Hi Rick. 

I saw that you reported the problem in an earlier [PR](https://github.com/BVLC/caffe/pull/2084). I think that the changes I made to the CMake build would make building dlls possible (given that we put the CAFFE_EXPORT macro in every file which I did not do) but did not have time to try. 

Can you confirm that the GPU problem is there with my fork too?

If you want to submit me a PR so that I can try your changes and send you some feedback on what could be done to have GPU support I would be willing to help.

Otherwise, I guess you could wrap a static library in an other pure C++ DLL (or mixed CLR) and than interop with this one instead?

**Comment by Geekrick88** [comment]
Thank you. I will make the same changes in your visual studio branch and see how it goes.
