### ISSUE TITLE
32 bit Build for windows fail

### ISSUE THREAD

**Issue by gopi1989** [willyd/caffe-builder#7]
Hi Willyd,

Thanks for your CAFFE windows builder. I builded the CAFFE in 64 bit Machine.Also 
implemented the CAFFE to my Project but i used the following Requirements 
1. CUDA 6.5
2. VS2013
3. OpenCV3.0

I have an issue like this while i try to build the CAFFE  for 32 bit.Will  you suggest a solution to me.
1. Error	141	error : invalid combination of type specifiers [E:\CAFFE_32\caffe-builder-master\build_32\Caffe-prefix\src\Caffe-build\src\caffe\caffe.vcxproj]	e:\caffe_32\caffe-builder-master\build_32\install\include\H5public.h	152	1	Caffe
2. Error	275	error : invalid combination of type specifiers [E:\CAFFE_32\caffe-builder-master\build_32\Caffe-prefix\src\Caffe-build\src\caffe\caffe.vcxproj]	e:\caffe_32\caffe-builder-master\build_32\install\include\H5public.h	152	1	Caffe

**Comment by willyd** [comment]
@gopi1989 Thanks for your interest in caffe-builder. As mentioned in the [README](https://github.com/willyd/caffe-builder/blob/master/README.md) this was only tested with 64 bit code. I never tried or intended to use caffe with a 32 bit application. From what I can see the error seems to be related to HDF5... with that little information is it hard to tell what your problem is.

Beware that the version of OpenBLAS downloaded by Caffe Builder is 64 bit. So you will need to download a 32 bit version of OpenBLAS. It should be enough to change the URL in OpenBLAS.cmake.

 I am afraid I cannot help you more with this.

**Comment by gopi1989** [comment]
@willyd Thanks for your Reply!!!.Sure will change the OpenBLAS 32 bit Package and let me update the build status to you ...

**Comment by gopi1989** [comment]
@willyd  I tried the Caffe-Builder with OpenBLAS 32 bit Package.Again facing the same Issues

**Comment by gopi1989** [comment]
@willyd  I builded the CAFFE for 32 bit windows successfully. I also did all the CAFFE related works.
Thousands and thousands of Thanks for your contribution

**Comment by willyd** [comment]
@gopi1989 Nice. Did you modify any code in caffe-builder or caffe? Other people could benefit from your work too. Can you submit your changes as a PR?

**Comment by gopi1989** [comment]
Changes I did to build CAFFE for 32 bit:
1. Changed the OpenBLAS download link for 32 bit.
2. You got the error in the following line in "H5public.h" file
      #if H5_SIZEOF_SIZE_T==H5_SIZEOF_INT
     typedef int ssize_t;
     # define H5_SIZEOF_SSIZE_T H5_SIZEOF_INT
3. Simply Changes the flag to "1" 
      #if H5_SIZEOF_SIZE_T==1

**Comment by MdAshrafulAlam** [comment]
where did you change the OpenBLAS download link for 32 bit? and, where can i find H5public.h file?
